config/routes.rb
Rails.application.routes.draw do
  get 'users/new'
  get 'users/edit'
  get 'sessions/index'
  root 'static_page#home'
  get 'screens/index'
  get 'sessions/new'
  post 'sessions/create'
  get 'sessions/destroy'
  # get 'theaters/index'
  # root 'theaters#index'
  resources :theaters do 
    resources :screens do
      resources :movies
    end
  end
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/author.rb
class Author < ApplicationRecord
end

app/models/book.rb
class Book < ApplicationRecord
end

app/models/customer.rb
class Customer < ApplicationRecord
end

app/models/employee.rb
class Employee < ApplicationRecord
  belongs_to :theater
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :users
 
  belongs_to :screen 
  validates :screen_id, presence: true , uniqueness: true 
  # validate :unique_screen


  # def unique_screen
  #   binding.pry
  #   screens = []
  #   self.screen do |sc|
  #     if !screens.include?(sc)
  #       screens.push(sc)
  #     end
  #   end
  # end
end

app/models/screen.rb
class Screen < ApplicationRecord
  has_many :users
  belongs_to :theater
  has_one :movie 
  validates :s_name , presence: true 
end

app/models/theater.rb
class Theater < ApplicationRecord
  has_many :users
  has_many :screens
  has_many :employees
end

app/models/user.rb
class User < ApplicationRecord
	validates :email, presence: true , length: { maximum: 150 },format: {with: URI::MailTo::EMAIL_REGEXP},uniqueness: { case_sensitive: false}
	has_secure_password
	validates :password, length: { minimum: 6 } , allow_blank: true
	
	belongs_to :movie , optional: true
  	belongs_to :theater ,optional: true
  	belongs_to :screen ,optional: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	include SessionsHelper
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
	def index
		@movies = Movie.all
	end
	def show
		@movie = Movie.find(params[:id])
	end
end

app/controllers/screens_controller.rb
class ScreensController < ApplicationController
  def index
    @screens = Screen.all
  end

  def show
    @theater = Theater.find(params[:theater_id ])
    @screen = Screen.find(params[:id])
  end

  def new 
    @screens = Screen.new
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def index
  end

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email])
    if user && user.authenticate(params[:session][:password])
        log_in user
        flash[:notice] = "Login Successfully"
        redirect_to theaters_path
    
    else
      flash[:alert] = "Missing Fields"
      # render 'new'
      # render :action => "new.html.erb"
      
      redirect_to sessions_new_path
    end
  end
  
  def destroy
    log_out if logged_in?
    flash[:notice] = "Logout Successfully"
    redirect_to root_path
  end
end




# -----------------------------------------------------------------------------

  # def log_in(user)
  #   # binding.pry
  #   session[:user_id] = user.id
  # end

  # def log_out
  #   session.delete(:user_id)
  #   @current_user = nil
  # end

  # def current_user
  #   @current_user ||= User.find_by(id: session[:user_id])
  # end



  # (helper_method :current_user) bcoz of that line this method is avaliable for all class   






  # def logged_in?
  #   !current_user.nil?
  # end

app/controllers/theaters_controller.rb
class TheatersController < ApplicationController
  def index
    @theaters = Theater.all
  end

  def show 
    @theater = Theater.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def show
    # @theater = Theater.find(params[:theater_id])
    # @movie = Movie.find(params(:movie_id))
    # @screen = Screen.find(params(:theater_id))
    @user = User.find(params[:id])
    # @movie = Movie.find(params[:movie_id])
  end
  
  def new
    @user = User.new
  end


  def create 
    @user = User.new(user_param)
    if @user.save
      log_in @user
      flash[:notice] = "Signup Successfully"
      redirect_to theaters_path
    else
      # flash[:alert] = "Missing Fields"
      render 'new',status: :unprocessable_entity
      # redirect_to users_new_path
    end
  end

  def edit
    @user = User.find(params[:user_id])
    @movie =Movie.find(params[:movie_id])
    @theater = Theater.find(params[:theater_id])
    @screen = Screen.find(params[:screen_id])
  end

  def update
    binding.pry
    @user = User.find(params[:user_id])
    if @user.update(cus_params)
      redirect_to user_path(@user)
    end
  end




  private
  def user_param
    params.require(:user).permit(:email,:password,:password_confirmation)
  end

  def cus_params
    params.require(:user).permit(:name,:theater_id,:screen_id,:movie_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/screens_helper.rb
module ScreensHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	 def log_in(user)
    session[:user_id] = user.id
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

end

app/helpers/static_page_helper.rb
module StaticPageHelper
end

app/helpers/theaters_helper.rb
module TheatersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/screens/show.html.erb
<head>
	<div style="text-align:right;">
	<%= link_to "Log out", sessions_destroy_path, method: :delete %>
    </div>
</head>

<h1>Currently play</h1>
<h3>Movie : <%= @screen.movie.m_name %></h3>


<%= link_to "Continue",edit_user_path(user_id: current_user.id, screen_id: @screen.id, movie_id: @screen.movie.id, theater_id: @theater.id)%>


<%= link_to "Home",  theaters_path%>

app/views/theaters/index.html.erb
<head>
	<div style="text-align:right;">
	<%= link_to "Log out", sessions_destroy_path, method: :delete %>
    </div>
</head>

<%= render "layouts/flash" %>

<h1>Book my show</h1>

<h1>Theaters</h1>

<ul>

	<% @theaters.each do |ele| %>
	<li>
		<%= link_to ele.t_name ,theater_path(ele) %>
	</li>
	<% end %>
</ul>

app/views/theaters/show.html.erb
<head>
	<div style="text-align:right;">
	<%= link_to "Log out", sessions_destroy_path, method: :delete %>
    </div>
</head>

<h1>Available Screen</h1>
<ul>
	<% @theater.screens.each do |screen| %>
	<li>
		<%= link_to  screen.s_name , theater_screen_path(screen, theater_id: @theater.id)%>   
	</li>
	<% end %>
</ul>
<%= link_to "Home",  theaters_path%>

app/views/users/edit.html.erb
<%= form_for @user, url: user_path(user_id: current_user.id) do |f| %>
	<div>
		<%= f.hidden_field :screen_id, value: @screen.id %>
		<%= f.hidden_field :movie_id, value: @movie.id %>
		<%= f.hidden_field :theater_id, value: @theater.id %>

		<%= f.submit "Book Your Ticket" %>
	</div>
<% end %>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<%= render "layouts/flash" %>
<body style="background-color:whitesmoke;">

<div style="text-align:center;"> 

<h1>Sign up</h1>
		<%= form_for @user do |f| %>
		
			<%= f.label :email %><br>
			<%= f.email_field :email %> <br>

			
			<% @user.errors.full_messages_for(:email).each do |message| %>
      			<div><%= message %></div>
    				<% end %>
  				<br>

			<%= f.label :password %><br>
			<%= f.password_field :password %><br>
			<% @user.errors.full_messages_for(:password).each do |message| %>
      			<div><%= message %></div>
    				<% end %>
  				<br>

			<%= f.label :password_confirmation, "Confirmation" %><br>
			<%= f.password_field :password_confirmation %> <br><br>
			<% @user.errors.full_messages_for(:password_confirmation).each do |message| %>
      			<div><%= message %></div>
    				<% end %>
  				
			
			<%= f.submit "Create my account"%>
			
		<% end %>
</div>

<p>old user? <%= link_to "login now!", sessions_new_path %></p>
<%= link_to "Back", root_path %>
</body>

app/views/users/show.html.erb
<head>
	<div style="text-align:right;">
	<%= link_to "Log out", sessions_destroy_path, method: :delete %>
    </div>
</head>
<body style="background-color:whitesmoke;">
	<div>
		<h1>Your booking is done </h1>
		<h2>booking ID: <%= @user.email %></h2>
		<h3>And your Theater is : <%= @user.theater.t_name %></h3>
		<h4>And the Movie name: <%= @user.movie.m_name %> Screen: <%= @user.screen.s_name%></h4>
		
		<h3><%=link_to "plan change ??" , theaters_path %></h3>
	</div>
</body>